CREATE DATABASE IF NOT EXISTS blog;

USE blog;

CREATE TABLE IF NOT EXISTS users (
  id INT NOT NULL AUTO_INCREMENT,
  username VARCHAR(31) NOT NULL,
  password VARCHAR(31) NOT NULL,
  email VARCHAR(255) NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS posts (
  id INT NOT NULL AUTO_INCREMENT,
  userId INT NOT NULL,
  title VARCHAR(127) NOT NULL,
  filPath VARCHAR(255) NOT NULL,
  PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS comments (
  id INT NOT NULL AUTO_INCREMENT,
  userId INT NOT NULL,
  postID INT NOT NULL,
  content VARCHAR(255),
  likes INT,
  dislikes INT,
  PRIMARY KEY (id)
);

ALTER TABLE posts ADD INDEX title;